### PR TITLE
switch 0 to false for more db support, fixes #411

### LINKED ISSUE #411: Postgres error in admin.rb
This query throws an error:
```
def destroy_orphaned
    destroy_all '(select count(*) from people where people.admin_id = admins.id and people.deleted = 0) = 0 and template_name is null'
end
```

```
ERROR:  operator does not exist: boolean = integer
LINE 1: ...re people.admin_id = admins.id and people.deleted = 0) = 0 a...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

### PR DESCRIPTION
**Pull request by jscheel**

### CODE REVIEW

**Comment by seven1m** [comment]
Thanks for the fix!

Have you tested this with MySQL? I don't think you can use `false` in a MySQL query.

Better yet, let's create a test so we can be sure this works on both DBs.

**Comment by jscheel** [comment]
Hmm, you may have to use uppercase `FALSE` in mysql. IIRC, `FALSE` and `0` are essentially the same, except for certain edge cases.

**Comment by jscheel** [comment]
Can you please explain what an orphaned admin is? Shouldn't the check be for `TRUE` instead of `FALSE`, since it seems to be looking for admins that are no longer associated with people? I may be totally misunderstanding what's happening here :)

**Comment by seven1m** [comment]
This code could definitely be clearer, but it is as intended.

If there are zero non-deleted people attached to a non-template admin record, then the admin record is "orphaned" and should be destroyed.

orphaned_admins

**Comment by seven1m** [comment]
Closing in favor of #415.

**Comment by jscheel** [comment]
@seven1m thanks! Sorry I haven't had time to look into this. Had a family emergency to deal with over the past week.

**Comment by seven1m** [comment]
No worries! Glad you found the bug and gave me the motivation to clean this up! :smiley_cat:

**Pull request closed without merging**
