### PR TITLE
Added anchors to custom_report.rb

### LINKED ISSUE #609: Validation: /app/models/custom_report.rb
Hi. Looks like the format validation in CustomReport is insufficient:

``` Ruby
  validates :filters, format: /:/, allow_blank: true
  validate :filter_content
```

Maybe there should be a bit more validation anchors to improve security? If needed, I can create PR for this.

Thank you.

### PR DESCRIPTION
**Pull request by Newman101**
Added anchors to ```app/models/custom_report.rb```. Fixes #609.

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
👍 Looks good.

**Comment by Newman101** [comment]
Looks like something is failing. I need to see the CI report for details. It must be the field configuration, since the rest of the code is configured to work without anchors.

**Comment by Newman101** [comment]
Can you confirm me what format validator is supposed to contain please? Words? Or numbers as well? Thanks.

**Comment by Newman101** [comment]
Got it: ```\A+\w+:+\w+\z``` should do this trick. Let me re-commit.

**Comment by Newman101** [comment]
Looks like this is not just one field.

```Ruby
      @custom_report = FactoryGirl.create(
                          :custom_report,
                          category: '3',
                          filters: 'name:Doe Group; some:rubbish')
```

**Comment by Newman101** [comment]
OK, here's what I am going to do: Build a RegExp using that test case. Based on my earlier work this should not be hard case any longer. I just need to add the whitespace characters, word, semicolon, and another whitespace character in between.

**Comment by Newman101** [comment]
```\A+\w+:+\w+\s+\w+\w+;+\s+\w+:+\w+\z``` matches the string ```name:Doe Group; some:rubbish```.

**Comment by Newman101** [comment]
I think this is a special case. 

```Failure/Error: @custom_report = FactoryGirl.create(:custom_report)
     
     ActiveRecord::RecordInvalid:
       Validation failed: Filters Filters must contain a colon, in the form field:value.
```

This error happens all the time. RegExp is valid, but somehow the Filter does not accept the colon.

**Comment by seven1m** [comment]
@Newman101 thanks for taking a peek -- I'll work on this one when I get a few minutes. Thanks again!

**Comment by Newman101** [comment]
You're welcome. Looks like the ActiveRecord does not validate even with valid RegExp. Please have a look when you have time.

**Comment by Newman101** [comment]
Closing this one as I was unable to get ActiveRecord to validate.

**Pull request closed without merging**
