### PR TITLE
Translate to czech - file accounts.yml

### PR DESCRIPTION
**Pull request by jsuchome**
I am testing translate to czech and use github system. I hope that it
will be ok because I am newbe here.

(cherry picked from commit 37b28ab924bca717eff085ceae644a84c37153d3)

### CODE REVIEW

**Comment by jsuchome** [comment]
Now I see, the encoding is really broken...

**Comment by seven1m** [comment]
Is this good to merge?

**Comment by jsuchome** [comment]
I'm still confused by that Hakiri message - is it just complaining about nokogiri version?

**Comment by seven1m** [comment]
@jsuchome don't worry about it. I'll take a look at it later. We can merge this when you're ready.

**Comment by jsuchome** [comment]
@seven1m yes, the text is correct (and you can close the original PR, https://github.com/churchio/onebody/pull/621)

(I'm getting that injection warning in https://github.com/churchio/onebody/pull/624 as well, is it because of files with HTML tag?)

**Comment by seven1m** [comment]
I think we just need to `bundle update nokogiri` but I'm not sure.

**Pull request merged**
