### PR TITLE
WIP Heroku: DO NOT MERGE

### PR DESCRIPTION
**Pull request by aunderwo**
Hi
I've managed to get onebody working on heroku but there were quite a few changes that may not fit with recent commits

First locally I ran the following command as a user that had permissions to make a pg user
```
createuser  --no-adduser onebody
rake db:create db:migrate db:schema:load db:seed
```
checked that this was working locally and then made changes necessary for heroku
  1.   Gemfile.lock needs to be in the repo si added this
  2.   pg gem needs to specified explicitly in Gemfile rather than wrapped in the block that determines the db flavour from database.yml
  3.   added the ENV variable SERVE_ASSETS to heroku `heroku config:set SERVE_ASSETS='true'` in order to get assets to be served by rails
  4.   corrected a Mysql-specific exception that was causing asset compilation to fail
  5.   secrets.yml needed to be in the repo so used ENV variables to define these

    ```
    production:
        secret_token: <%= ENV['SECRET_TOKEN'] %>
        secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
    ```
 Again used `heroku config set X='Y'`
  6.   added S3-specific configs to production.rb. AWS keys and buckets used ENV variables

    ```
    :s3_credentials => {
      :bucket => ENV['S3_BUCKET_NAME'],
      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
    ```
 Again used `heroku config set X='Y'`
  7.   added specific version of aws-sdk `gem 'aws-sdk', '~> 1.5.7'`

All is working well including image uploads. However not sure how this code should be used whilst not breaking the 'normal' Mysql-based install.
Suggestions welcome

### CODE REVIEW

**Comment by seven1m** [comment]
@aunderwo this is awesome!!! I'll do some thinking about how we can make this work.

Thank you!

**Comment by seven1m** [comment]
@churchio/committers @churchio/contributors What do you guys think about having a dedicated, long-living `heroku` branch? That way, we can include all these changes there.

**Comment by seven1m** [comment]
Related: #215

**Comment by ZucchiniZe** [comment]
I personally think that having a dedicated heroku branch would be awesome. I could add the deploy to heroku button if I have time.

**Comment by seven1m** [comment]
@ZucchiniZe any help you can provide would be appreciated!

**Comment by seven1m** [comment]
@ZucchiniZe do you think it would be hard for us to keep the `heroku` branch up-to-date with `master`? Since I don't use Heroku, I'm hoping someone will step up to take responsibility for it, keep it up-to-date, and test that nothing breaks on it from time to time.

**Comment by ZucchiniZe** [comment]
I could rebase/merge it every once it a while to make sure it stays up with `master`

**Comment by seven1m** [comment]
@aunderwo or @ZucchiniZe can one of you please (at your convenience) a branch called `heroku` on this repo (I gave you access just now) and push these changes there?

Also, can you use Ruby 1.9+ hash syntax please. :smiley: 

I was thinking I (or someone) could create a daily cron script that merges master into the `heroku` branch. Upon failure merging, the script could create a new issue on GitHub so we could be notified of a conflict. Thoughts?

**Comment by DouglasMeyer** [comment]
Hello, I wanted to checkout onebody working on heroku. I was going to start with this branch and merge-in master, but there seemed to be issues in doing so. I was able to make some [similar changes](https://github.com/DouglasMeyer/onebody/compare/heroku) to get it running. Just wondering if you would be interested. Thanks.

**Comment by seven1m** [comment]
@DouglasMeyer I have some ideas I'm trying over in the [heroku-support](https://github.com/churchio/onebody/compare/heroku-support) branch. I'd like to try to keep this from becoming a maintenance nightmare with branches. If it all works, I'll merge the `heroku-support` branch into master -- users who are deploying to Heroku will run `script/build_for_heroku` and make a commit before pushing. We'll see how it goes! :smiley_cat:

**Pull request closed without merging**
