### PR TITLE
updated ruby patch version & locked rails for latest stable

### PR DESCRIPTION
**Pull request by ferdinandrosario**
updated ruby for latest patch and locked rails with specific version. this will helps to avoid confusion about rails version.

### CODE REVIEW

**Comment by seven1m** [comment]
@ferdinandrosario thanks. Please also update .travis.yml and circle.yml too.

I don't see the need for the Rails version in the gemfile. It's locked in the Gemfile.lock file already.

**Comment by ferdinandrosario** [comment]
updated circle CI .yml and travis won't need since we specified as 2.2, that will ensure that travis always checks against ruby-2.2 latest patch.

Regarding rails version if we are not specific on gemfile then, when a new rails version release it will end up installing the new version whoever doing fresh bundle install.

do you still wants me to remove the rails version from Gemfile? if so please tell me I'll remove it...

**Comment by seven1m** [comment]
@ferdinandrosario the Gemfile.lock is a part of the repo and ensures that only the locked version of Rails will be installed. We don't need it in the Gemfile. Thanks!

**Comment by ferdinandrosario** [comment]
@seven1m I removed version from Gemfile. :+1:

**Comment by seven1m** [comment]
Thanks!

**Pull request merged**
