### PR TITLE
Changing tabs then clicking Back does not work #552

### PR DESCRIPTION
**Pull request by acbilimoria**
Comments and feedback always welcome!

The one remaining bug that I see with this is:
Click through the tabs, then use the back button, the previously selected tab stays grey until clicking anywhere on the page.

### CODE REVIEW

**Comment by seven1m** [comment]
@acbilimoria actually I was hoping we could fix this here: https://github.com/churchio/onebody/blob/master/app/assets/javascripts/app/tabs.js.coffee

We already have logic for selecting the proper tab if the URL contains the tab id. I think adding pushstate/popstate event handlers could make this work on any page without specifically hard-coding tab ids and such.

Let me know if that makes sense or not!

**Comment by acbilimoria** [comment]
Oh yeah I didn't even see that file when I was looking at solutions.  Are you looking for something more like this?   https://gist.github.com/acbilimoria/a1df0dd3329d9638b6e3#file-tabs-js-coffee

**Comment by seven1m** [comment]
@acbilimoria yes, but it should also work when the page first loads too, i.e. a bookmark or a link from an email. Thanks!

**Comment by acbilimoria** [comment]
Good point!  Thanks so much for the help!  https://gist.github.com/acbilimoria/a1df0dd3329d9638b6e3#file-tabs-js-coffee

**Comment by acbilimoria** [comment]
I have a partial solution.  The problem is that when you press back until the URL doesn't have a hash ( i.e. /groups/3/edit#tab-about :back: /groups/3/edit ) the tabs don't change.  Code like this

$(window).on 'popstate', ->
  if location.hash.match(/^#tab-/)
    $(".nav-tabs a[href=##{location.hash.replace('#tab-', '')}]").tab('show')
  else if location.hash.match('')
    $(".nav-tabs a[href]").first().tab('show')
    return

fixes that problem but causes another -- it acts like the user clicked and overwrites the browser's forward history.

**Comment by seven1m** [comment]
@acbilimoria I'm sorry, not sure where this is at. Do you think it's not possible to fix this?

**Comment by acbilimoria** [comment]
I actually think I have a solution but the code is a bit inelegant.  The
remaining issue was that clicking back from a fragment to non fragment url
didn't change tabs.

My solution is to check the page for an active tab and if one exists use
window replace state to change the url to a fragment url.

I'll commit it in the next day or two and ping you

**Comment by acbilimoria** [comment]
@seven1m ping!

**Comment by seven1m** [comment]
@acbilimoria thanks! I'll play with this a bit later.

**Pull request merged**
