### PR TITLE
Feature/tasks as a group

### LINKED ISSUE #471: Let Tasks be assigned to groups
My church's current church management software allows groups to have Projects that track any volunteer work, crafts, etc. that each group is doing. I think OneBody's Tasks could be used similarly, a task could be assigned to a group instead of a single person.

### PR DESCRIPTION
**Pull request by AndyGauge**
Adds an All Members option in drop down for Assigned To when creating/editing a Task.  This selection will 'assign' the Task to all members of the group.  Tasks show up in the sidebar, and in the tasks view for the members of the group and the group.  

Profiling of large groups may be necessary.  The database time for groups with many members, with each member having many tasks could get expensive when saving tasks.  This calculation may need to be moved to a process_queue.

Fixes #471

### CODE REVIEW

**Comment by seven1m** [comment]
@AndyGauge I'd like to merge this, but there are some code style issues that make me :grimacing:. Can you run [rubocop](https://github.com/bbatsov/rubocop) and clean up the issues it points out (only with your new code -- you can ignore existing rubocop warnings for code you didn't write).

Thanks!!!

**Comment by AndyGauge** [comment]
By far the most important thing I learned this week: Ruby has a [style guide](https://github.com/bbatsov/ruby-style-guide).  Thank you Tim for rubocop link.  Is the haml OK or should I be adding a lint to the workflow?

**Comment by seven1m** [comment]
Haml looks fine to me, thanks.

**Comment by seven1m** [comment]
@AndyGauge this looks much better ... ok to merge now?

**Comment by AndyGauge** [comment]
OK to merge, thank you.

**Comment by seven1m** [comment]
Sweet!

**Pull request merged**
