### PR TITLE
check incoming email for site based on site domain or email_host domain

### PR DESCRIPTION
**Pull request by aunderwo**
Enables mail domains other than app domain if set via email_host setting

### CODE REVIEW

**Comment by aunderwo** [comment]
I'm not if the test 'given message to group in second site from wrong address -> delivers in proper site' worked as expected since the get_site method had a = rather than ==. The way I look at the code if an incoming email has a to address to a domain it should be redirected (by mailgun?) to the emails controller of the correct site. Therefore the notifier receive method will never get past the line 
```
return unless get_site(email)
```
and therefore will never bounce back an email using the unknown_person subject/body.

Is this correct?

**Comment by seven1m** [comment]
The test is right and the `=` (assignment) was correct.

The line should be:

```ruby
return Site.current if (Site.current = Site.where(host: address.downcase.split('@').last).first || Site.where(email_host: address.downcase.split('@').last).first
```

And we should add a test to ensure email from the `email_host` is being accepted for the proper site as well.

**Comment by aunderwo** [comment]
Ok. I think I understand. The assignment will return nil if Site.where(host: address.downcase.split('@').last is nil? Is that right?

**Comment by seven1m** [comment]
The assignment will set `Site.current` to nil, but it won't return from the method.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://harmonicaschool.fr/scenario.php?ivj5q>

 

klaus@hebsgaard.dk

**Pull request closed without merging**
