### PR TITLE
Refactored RSpec custom report  model spec

### PR DESCRIPTION
**Pull request by x-light**
Got inspired to tidy up!

### CODE REVIEW

**Comment by seven1m** [comment]
Cool!

Though, you can't use the shorthand `it { should ... }` form unless you set the subject.

**Comment by x-light** [comment]
Like [this](https://github.com/x-light/onebody/commit/32611d1ff42cc7a570cf33cb45cac91c02cde84f#diff-20a7cd674eab181dfbd0d44699aa1ec7R4)? Then, can I remove the @custom_report variable and just write things like ```title = nil```?

**Comment by seven1m** [comment]
@x-light not quite. If you use `subject`, then don't use `@custom_report`.

You'd have to write, e.g. `subject.title = nil`.

Check out http://www.relishapp.com/rspec/rspec-core/docs/subject

**Comment by x-light** [comment]
Sweet, thanks. I vaguely remember that, but it was about 15 zillion tutorials ago :smile: 
Odd that it didn't error though, but nvm. I'll update it tomorrow. Thanks!

**Comment by seven1m** [comment]
TDD: Red, Green, Refactor :smile: 

Your test should have been failing first, then passing.

**Comment by x-light** [comment]
I've spent some time (attempting to) refactor this spec today, and its going to take me longer than I thought to do so. I'm going to close this PR and come back to it when I've got some other things off my plate.

**Pull request closed without merging**
